spring:
  config:
    active:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        show_sql: false
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email


logging.level:
  org.hibernate.SQL: debug # log 파일로 남길 수 있다.
  org.hibernate.orm.jdbc.bind: trace # 바인딩 파라미터도 볼 수 있는 option

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expire-hour:
    access-token: 2
    refresh-token: 72 # 3일
